//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mis_DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=193.227.24.12;Initial Catalog=menofeya;Persist Security Info=True;Use" +
            "r ID=admin;Password=admin")]
        public string misConnectionString {
            get {
                return ((string)(this["misConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=193.227.24.12;Initial Catalog=menofeya;Persist Security Info=True;Use" +
            "r ID=admin")]
        public string MnfUniversityConnectionString {
            get {
                return ((string)(this["MnfUniversityConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=193.227.24.12;Initial Catalog=menofeya;Persist Security Info=True;Use" +
            "r ID=admin")]
        public string MisDBConnectionString {
            get {
                return ((string)(this["MisDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=193.227.24.22;Initial Catalog=menofeya;Persist Security Info=True;Use" +
            "r ID=portal_admin")]
        public string MisConnectionString1 {
            get {
                return ((string)(this["MisConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sqlsrvr;Initial Catalog=menofeya;Integrated Security=True")]
        public string menofeyaConnectionString {
            get {
                return ((string)(this["menofeyaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=193.227.24.22\\sqlserver;Initial Catalog=menofeya;Persist Security Inf" +
            "o=True;User ID=portal_admin")]
        public string menofeyaConnectionString1 {
            get {
                return ((string)(this["menofeyaConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLADE-03\\SQLSERVER;Initial Catalog=menofeya;Persist Security Info=Tru" +
            "e;User ID=portal_admin")]
        public string menofeyaConnectionString2 {
            get {
                return ((string)(this["menofeyaConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLADE-03\\SQLSERVER;Initial Catalog=menofeya;Integrated Security=True")]
        public string menofeyaConnectionString3 {
            get {
                return ((string)(this["menofeyaConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.1.13;Initial Catalog=menofeya;Persist Security Info=True;User " +
            "ID=portal.staff")]
        public string menofeyaConnectionString4 {
            get {
                return ((string)(this["menofeyaConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.1.13;Initial Catalog=menofeya;User ID=portal.staff")]
        public string menofeyaConnectionString5 {
            get {
                return ((string)(this["menofeyaConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.1.13;Initial Catalog=menofeya;User ID=portal.staff;Password=Ju" +
            "i@50liRE54!;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False")]
        public string menofeyaConnectionString6 {
            get {
                return ((string)(this["menofeyaConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-L8GO34BPSS8;Initial Catalog=MnfPortals;Integrated Security=True;C" +
            "onnect Timeout=30;Encrypt=False;Trust Server Certificate=False")]
        public string MnfPortalsConnectionString {
            get {
                return ((string)(this["MnfPortalsConnectionString"]));
            }
        }
    }
}
