<%@ Page Title="" Language="C#" MasterPageFile="~/Masterpages/SiteMaster.master" AutoEventWireup="true" Inherits="Admin_Create_Roles" CodeBehind="Create_Roles.aspx.cs" %>

<%@ Import Namespace="Common" %>

<asp:Content ID="Content3" ContentPlaceHolderID="MainContentPlaceHolder" runat="Server">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57986194-1', 'auto');
  ga('send', 'pageview');

</script>    
<table style="float: <%= StaticUtilities.FloatLeft %>" width="100%" dir="ltr">
        <tr>
            <td class="style1">
                <asp:Button ID="Button1" runat="server"
                    Text="Add New" CssClass="_button" OnClick="Button1_Click1" />
            </td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td class="style1">
                <asp:Label ID="LblMsg" runat="server"></asp:Label>
            </td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td colspan="5">
                <asp:GridView ID="GridView1" runat="server" AllowPaging="True"
                    AutoGenerateDeleteButton="True" DataSourceID="LinqDataSource2"
                    AutoGenerateEditButton="True"
                    OnRowUpdating="UpdateRecord"
                    OnRowDeleting="DeleteRecord"
                    AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="RoleId"
                    OnRowCancelingEdit="GridView1_RowCancelingEdit"
                    OnRowCommand="GridView1_RowCommand" CellPadding="4" ForeColor="#333333"
                    GridLines="None">
                    <Columns>

                        <asp:TemplateField HeaderText="Application Name">
                            <ItemTemplate>
                                <%# Eval("aspnet_Application.ApplicationName")%>
                            </ItemTemplate>
                            <EditItemTemplate>

                                <asp:DropDownList ID="DropDownList1" runat="server"
                                    DataSourceID="LinqDataSource1" DataTextField="ApplicationName"
                                    DataValueField="ApplicationId">
                                </asp:DropDownList>
                                <asp:LinqDataSource ID="LinqDataSource1" runat="server"
                                    ContextTypeName="Portal_DAL.PortalDataContextDataContext" TableName="aspnet_Applications">
                                </asp:LinqDataSource>
                            </EditItemTemplate>
                            <FooterTemplate>
                                <asp:DropDownList ID="DropDownList1" runat="server"
                                    DataSourceID="LinqDataSource1" DataTextField="ApplicationName"
                                    DataValueField="ApplicationId">
                                </asp:DropDownList>
                                <asp:LinqDataSource ID="LinqDataSource1" runat="server"
                                    ContextTypeName="Portal_DAL.PortalDataContextDataContext" TableName="aspnet_Applications">
                                </asp:LinqDataSource>
                            </FooterTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Role Name">
                            <ItemTemplate>
                                <asp:Label ID="LblRoleName" runat="server" Text='<%# Eval("RoleName") %>' Visible="true"></asp:Label>
                                <%--<%# Eval("RoleName")%>--%>
                                <%--    <asp:Label ID="LblRoleID" runat="server" Text='<%# Eval("RoleID") %>' Visible ="false"></asp:Label>--%>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:Label ID="LblRoleID" runat="server" Text='<%# Eval("RoleID") %>' Visible="false"></asp:Label>

                                <asp:TextBox ID="txtRole" runat="Server" Text='<%# Eval("RoleName") %>'></asp:TextBox>
                                <asp:RequiredFieldValidator ID="req2" runat="Server" Text="*" ControlToValidate="txtRole"></asp:RequiredFieldValidator>
                            </EditItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="txtRole" runat="Server" Text='<%# Eval("RoleName") %>'></asp:TextBox>
                                <asp:RequiredFieldValidator ID="req2" runat="Server" Text="*" ControlToValidate="txtRole"></asp:RequiredFieldValidator>
                                <%--  <asp:Label ID="LblRoleID" runat="server" Text='<%# Eval("RoleID") %>' Visible ="false"></asp:Label>--%>
                            </FooterTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField>
                            <FooterTemplate>
                                <asp:Button ID="btnInsert" runat="Server" Text="Insert" CommandName="Insert" UseSubmitBehavior="False" />
                            </FooterTemplate>
                            <ItemStyle ForeColor="Red" />
                        </asp:TemplateField>
                    </Columns>
                    <EditRowStyle BackColor="#2461BF" />
                    <FooterStyle CssClass="grid_footer" BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle CssClass="grid_header" BackColor="#507CD1"
                        Font-Bold="True" ForeColor="White" />
                    <PagerSettings FirstPageText="First" LastPageText="Last" />
                    <PagerStyle CssClass="pgr" BackColor="#2461BF" ForeColor="White"
                        HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True"
                        ForeColor="#333333" />
                    <AlternatingRowStyle CssClass="grid_alternating" BackColor="White" />
                    <RowStyle CssClass="grid_item" BackColor="#EFF3FB" />
                    <SortedAscendingCellStyle BackColor="#F5F7FB" />
                    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                    <SortedDescendingCellStyle BackColor="#E9EBEF" />
                    <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>

                <asp:LinqDataSource ID="LinqDataSource2" runat="server"
                    ContextTypeName="Portal_DAL.PortalDataContextDataContext" EnableDelete="True"
                    EnableInsert="True" EnableUpdate="True" TableName="aspnet_Roles">
                </asp:LinqDataSource>
            </td>
        </tr>
        <tr>
            <td class="style1">&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
    </table>
</asp:Content>