//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=193.227.24.12;Initial Catalog=MisDB;Persist Security Info=True;User I" +
            "D=admin;Password=admin")]
        public string misConnectionString {
            get {
                return ((string)(this["misConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=193.227.24.12;Initial Catalog=MnfPortals;Persist Security Info=True;U" +
            "ser ID=admin")]
        public string MnfUniversityConnectionString {
            get {
                return ((string)(this["MnfUniversityConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=193.227.24.22;Initial Catalog=MnfPortals;Persist Security Info=True;U" +
            "ser ID=admin")]
        public string MnfPortalsConnectionString {
            get {
                return ((string)(this["MnfPortalsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=MnfPortals;Integrated Security=True")]
        public string MnfPortalsConnectionString1 {
            get {
                return ((string)(this["MnfPortalsConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=193.227.24.22;Initial Catalog=MnfPortals;Persist Security Info=True;U" +
            "ser ID=portal_admin;Password=P0rt@lAdm!n")]
        public string MnfPortalsConnectionString2 {
            get {
                return ((string)(this["MnfPortalsConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=193.227.24.22;Initial Catalog=MnfPortals;User ID=portal_admin")]
        public string MnfPortalsConnectionString3 {
            get {
                return ((string)(this["MnfPortalsConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=193.227.24.22\\sqlserver;Initial Catalog=MnfPortals;Persist Security I" +
            "nfo=True;User ID=portal_admin")]
        public string MnfPortalsConnectionString4 {
            get {
                return ((string)(this["MnfPortalsConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=193.227.24.22\\SQLSERVER;Initial Catalog=MnfPortals;Persist Security I" +
            "nfo=True;User ID=portal_admin")]
        public string MnfPortalsConnectionString5 {
            get {
                return ((string)(this["MnfPortalsConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLADE-03\\SQLSERVER;Initial Catalog=MnfPortals;Persist Security Info=T" +
            "rue;User ID=portal_admin")]
        public string MnfPortalsConnectionString6 {
            get {
                return ((string)(this["MnfPortalsConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=193.227.24.22\\SQLSERVER;Initial Catalog=MnfPortals;Persist Security I" +
            "nfo=True;User ID=portal_admin;Password=P0rt@lAdm!n")]
        public string MnfPortalsConnectionString7 {
            get {
                return ((string)(this["MnfPortalsConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=193.227.24.22\\SQLSERVER;Initial Catalog=MnfPortals;User ID=portal_adm" +
            "in;Password=P0rt@lAdm!n")]
        public string MnfPortalsConnectionString8 {
            get {
                return ((string)(this["MnfPortalsConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=193.227.24.22\\SQLSERVER;Initial Catalog=MnfPortals;User ID=portal_adm" +
            "in")]
        public string MnfPortalsConnectionString9 {
            get {
                return ((string)(this["MnfPortalsConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLADE-03\\SQLSERVER;Initial Catalog=MnfPortals;Integrated Security=Tru" +
            "e")]
        public string MnfPortalsConnectionString10 {
            get {
                return ((string)(this["MnfPortalsConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLADE-03\\SQLSERVER;Initial Catalog=MnfPortals;User ID=portal_admin")]
        public string MnfPortalsConnectionString11 {
            get {
                return ((string)(this["MnfPortalsConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLADE-03\\SQLSERVER;Initial Catalog=MnfPortals;Persist Security Info=T" +
            "rue;User ID=portal_admin;Password=P0rt@lAdm!n")]
        public string MnfPortalsConnectionString12 {
            get {
                return ((string)(this["MnfPortalsConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLADE-03\\SQLSERVER;Initial Catalog=menofeya;Persist Security Info=Tru" +
            "e;User ID=portal_admin")]
        public string menofeyaConnectionString {
            get {
                return ((string)(this["menofeyaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.1.22\\SQLSERVER;Initial Catalog=MnfPortals;Persist Security Inf" +
            "o=True;User ID=portal_admin")]
        public string MnfPortalsConnectionString13 {
            get {
                return ((string)(this["MnfPortalsConnectionString13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.1.22\\SQLSERVER;Initial Catalog=MnfPortals;Persist Security Inf" +
            "o=True;User ID=portal_admin;Connect Timeout=600")]
        public string MnfPortalsConnectionString14 {
            get {
                return ((string)(this["MnfPortalsConnectionString14"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLADE-03\\SQLSERVER;Initial Catalog=MnfPortals;Persist Security Info=T" +
            "rue;User ID=portal_admin;Connect Timeout=600")]
        public string MnfPortalsConnectionString15 {
            get {
                return ((string)(this["MnfPortalsConnectionString15"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLADE-03\\SQLSERVER;Initial Catalog=MnfPortals;Persist Security Info=T" +
            "rue;User ID=portal_admin;Password=P0rt@lAdm!n;Connect Timeout=600")]
        public string MnfPortalsConnectionString16 {
            get {
                return ((string)(this["MnfPortalsConnectionString16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=blade-03\\sqlserver;Initial Catalog=MnfPortals;Persist Security Info=T" +
            "rue;User ID=portal_admin")]
        public string MnfPortalsConnectionString17 {
            get {
                return ((string)(this["MnfPortalsConnectionString17"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLADE-03\\sqlserver;Initial Catalog=MnfPortals;Persist Security Info=T" +
            "rue;User ID=portal_admin")]
        public string MnfPortalsConnectionString18 {
            get {
                return ((string)(this["MnfPortalsConnectionString18"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-P291H5UCL1D;Initial Catalog=MnfPortals;Integrated Security=True")]
        public string MnfPortalsConnectionString19 {
            get {
                return ((string)(this["MnfPortalsConnectionString19"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-L8GO34BPSS8;Initial Catalog=MnfPortals;Integrated Security=True;C" +
            "onnect Timeout=30;Encrypt=False;Trust Server Certificate=False")]
        public string MnfPortalsConnectionString20 {
            get {
                return ((string)(this["MnfPortalsConnectionString20"]));
            }
        }
    }
}
