//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelName {
            get {
                return ResourceManager.GetString("CancelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to cancel this operation.
        /// </summary>
        internal static string CancelToolTip {
            get {
                return ResourceManager.GetString("CancelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry for this error the developer has been notified and the details are: .
        /// </summary>
        internal static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this record?.
        /// </summary>
        internal static string DeleteItemMessage {
            get {
                return ResourceManager.GetString("DeleteItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteName {
            get {
                return ResourceManager.GetString("DeleteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to delete this item.
        /// </summary>
        internal static string DeleteToolTip {
            get {
                return ResourceManager.GetString("DeleteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        internal static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditName {
            get {
                return ResourceManager.GetString("EditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to edit this item.
        /// </summary>
        internal static string EditToolTip {
            get {
                return ResourceManager.GetString("EditToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculties.
        /// </summary>
        internal static string Faculties {
            get {
                return ResourceManager.GetString("Faculties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image must be less than or equal to  &amp;1&amp; pixels in width and &amp;2&amp; pixels in height and the size must be no more than &amp;3&amp; MB..
        /// </summary>
        internal static string ImageInfoLabel {
            get {
                return ResourceManager.GetString("ImageInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string InsertName {
            get {
                return ResourceManager.GetString("InsertName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to insert this item.
        /// </summary>
        internal static string InsertToolTip {
            get {
                return ResourceManager.GetString("InsertToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        internal static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to create a new item.
        /// </summary>
        internal static string NewToolTip {
            get {
                return ResourceManager.GetString("NewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Translation Found for Article.
        /// </summary>
        internal static string NoTranslation {
            get {
                return ResourceManager.GetString("NoTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website you requested doesn&apos;t exist. Please check the url and try again..
        /// </summary>
        internal static string Owner_Not_Exist {
            get {
                return ResourceManager.GetString("Owner_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert New Item.
        /// </summary>
        internal static string PageBase_DepDetailsView_ItemCreated_Insert_New_Item {
            get {
                return ResourceManager.GetString("PageBase_DepDetailsView_ItemCreated_Insert_New_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Under Construction.
        /// </summary>
        internal static string Page_Under_Construction {
            get {
                return ResourceManager.GetString("Page_Under_Construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateName {
            get {
                return ResourceManager.GetString("UpdateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to update this item.
        /// </summary>
        internal static string UpdateToolTip {
            get {
                return ResourceManager.GetString("UpdateToolTip", resourceCulture);
            }
        }
    }
}
