//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MnfUniversity_Portals.UserControls.Editors.ArticleEditor.Details {
    
    
    public partial class ArticleDetailsViewUserControl {
        
        /// <summary>
        /// ArticleTemplateDetailsViewBasedControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MnfUniversity_Portals.UserControls.Base.DetailsBasedControlTemplate ArticleTemplateDetailsViewBasedControl;
        
        /// <summary>
        /// TranslationsLinqDataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinqDataSource TranslationsLinqDataSource;
    }
}
