 <meta content="text/html; charset=windows-1256" http-equiv=Content-Type>
<style type="text/css">
<!--
.style1 {
	color: #FFFFFF;
	font-weight: bold;
	font-family: "Times New Roman", Times, serif;
	font-size: 16pt;
	text-decoration: none;
	line-height: 150%;
}
.style2 {
	color: #FFCC00;
	font-size: 14pt;
	line-height: 150%;
}
.style7 {
	color: #FFFF00;
	font-size: 18pt;
	font-weight: bold;
	font-family: "PT Bold Heading";
	text-decoration: underline;
}
.style9 {
	color: #FFFF33;
	font-size: 18pt;
	font-weight: bold;
	font-family: "PT Bold Heading";
	text-decoration: underline;
	text-align: center;
}
a:link {
	text-decoration: none;
}
a:visited {
	text-decoration: none;
}
a:hover {
	text-decoration: none;
}
a:active {
	text-decoration: none;
}
-->
</style>

<!--#include file="temp/top.asp" -->
		
		<p class="style9">النشرة الاحصائيه للعام الجامعى 2008/2009        
		<p class="style9"> ديسمبر 2008  
		  <ul><li class="style1">الطلاب المقيدون (مرحلة البكالوريوس)
          <ul>
	        <li class="style2"><a href="DEC2008/1.asp" target="_blank" style="color:#FFCC00 ;text-decoration:none">أعداد الطلاب المقيدون فى العام الجامعى 2009/2008 - شبين الكوم </a></li>
            <li class="style2"><a href="DEC2008/2.asp" target="_blank" style="color:#FFCC00 ;text-decoration:none">أعداد الطلاب المقيدون فى العام الجامعى 2009/2008 - فرع السادات </a></li>
	        <li class="style2"><a href="DEC2008/3.asp" target="_blank" style="color:#FFCC00 ;text-decoration:none">أعداد الطلاب المقيدون فى العام الجامعى 2009/2008 (مستجد-منقول - باقى للاعاده)- شبين الكوم </a></li>
	        <li class="style2"><a href="DEC2008/4.asp" target="_blank" style="color:#FFCC00 ;text-decoration:none">أعداد الطلاب المقيدون فى العام الجامعى 2009/2008 (مستجد-منقول - باقى للاعاده)- فرع السادات </a></li>
          </ul>
	      </li>
	      <li class="style1"><a href="DEC2008/5.asp" target="_blank" style="color:#FFFFFF">الخريجون (مرحلة البكالوريوس)</a></li>
		  <li class="style1">الطلاب (مرحلة الدراسات العليا)
		    <ul>
		      <li class="style2"><a href="DEC2008/6.asp" target="_blank" style="color:#FFCC00">فرع شبين الكوم</a></li>
	          <li class="style2"><a href="DEC2008/7.asp" target="_blank" style="color:#FFCC00">فرع السادات</a> </li>
	        </ul>
		  </li>
		  <li class="style1">الاسكان الجامعى
		    <ul>
		      <li class="style2"><a href="DEC2008/8.asp" target="_blank" style="color:#FFCC00">الطلاب المقيمون بالمدن الجامعية موزعين على الكليات فى العام الجامعى2009/2008</a></li>
	          <li class="style2"><a href="DEC2008/9.asp" target="_blank"  style="color:#FFCC00">الطلاب المقيمين بقطاعات المدن الجامعية</a></li>
	        </ul>
		  </li>
		  <li class="style1">المستشفيات الجامعية
		    <ul>
		      <li class="style2"><a href="DEC2008/10.asp" target="_blank" style="color:#FFCC00">بيانات عن مستشفيات جامعة المنوفية من  2007/7/1حتى 2008/6/30</a></li>
            </ul>
		  </li>
		  <li class="style1">العاملين بالكادرالخاص
		    <ul>
		      <li class="style2"><a href="11.asp" target="_blank" style="color:#FFCC00">بيان يوضح اجمالى أعضاء هيئة التدريس والهيئة المعاونة فى 2008/12/1 - فرع شبين الكوم </a></li>
              <li class="style2"><a href="DEC2008/12.asp" target="_blank" style="color:#FFCC00">بيان يوضح اجمالى أعضاء هيئة التدريس والهيئة المعاونة فى 2008/12/1 - فرع السادات </a></li>
		    </ul>
		  </li>
		  <li class="style1">العاملين بالكادر العام
		    <ul>
		      <li class="style2">بيان يوضح اجمالى العاملين بالكادر العام فى 2008/9/30</li>
	        </ul>
		  </li>
		  </ul>		
		<!--#include file="temp/bottom.inc" -->
